"""add tone theme urgency columns to transcript_segments

Revision ID: 2e40d548f6ce
Revises: fc061ec9c122
Create Date: 2026-08-27 01:05:49.125207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e40d548f6ce'
down_revision: Union[str, None] = 'fc061ec9c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('tone', sa.String(length=50), nullable=True))
    op.add_column('transcript_segments', sa.Column('theme', sa.String(length=100), nullable=True))
    op.add_column('transcript_segments', sa.Column('urgency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_segments', 'urgency')
    op.drop_column('transcript_segments', 'theme')
    op.drop_column('transcript_segments', 'tone')
    # ### end Alembic commands ###
