"""add decisions column to recordings

Revision ID: fd4832b4d1e7
Revises: 2e40d548f6ce
Create Date: 2026-08-27 18:27:16.158320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4832b4d1e7'
down_revision: Union[str, None] = '2e40d548f6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('decisions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'decisions')
    # ### end Alembic commands ###
